/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/v1/maintenance/transaction/{transaction_reference}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Performs a maintenance operation on a given transaction
         * @description Performs a maintenance operation on a given transaction.
         */
        post: operations['performMaintenanceOperation'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/order': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Creates an order and a transaction based on payment details
         * @description This service allows you to execute transactions through API with no need
         *     to redirect your customer to the payment page hosted by HiPay. This
         *     service supports payments with credit or debit cards as well as
         *     alternative payment methods.
         *
         *     In **order** to make a payment with a credit or debit card, a token must
         *     have been generated beforehand. In fact, this service cannot receive
         *     credit or debit card numbers in clear. Instead, you must provide this
         *     service with a token associated to a card number. Use the HiPay
         *     Enterprise SDK for JavaScript in order to generate tokens.
         *
         *     If you need to make payments with alternative payment methods, you can
         *     use this service directly. Note that the use of some alternative payment
         *     products implies that you redirect your user to an external URL. In such
         *     a case, the `forwardUrl` parameter will be set with the appropriate URL.
         *     Moreover, the activation of *3-D Secure* also implies a redirection of
         *     your customer.
         */
        post: operations['requestNewOrder'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/transaction/{transaction_reference}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets details of existing transactions based on a transaction ID
         * @deprecated
         * @description Gets details of existing transactions based on a transaction ID.
         */
        get: operations['getTransactionByReference'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/transaction': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets details of existing transactions related to a given order
         * @deprecated
         * @description Gets details of existing transactions related to a given order. Deprecated, you can refer to [this page](https://developer.hipay.com/api-explorer/api-gateway#/transaction/get_api_consultation_transaction) for new endpoint
         */
        get: operations['getTransactionsByReference'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Maintenance
         * @description Maintenance model
         */
        Maintenance: {
            /**
             * @description The operation to perform on the transaction.
             *
             *         The payment gateway supports the following types of maintenance transactions.
             *
             *         | Operation Type | Description |
             *         | -------------- | ----------- |
             *         | `capture` | A request instructing the payment gateway to capture a previously-authorized transaction, i.e. transfer the funds from the customer’s bank account to the merchant’s bank account. This transaction is always preceded by an authorization. |
             *         | `refund` | A request instructing the payment gateway to refund a previously captured transaction. A captured transaction can be partly or fully refunded. |
             *         | `cancel` | A request instructing the payment gateway to cancel a previously authorized transaction. Only authorized transactions can be cancelled, captured transactions must be refunded. |
             *         | `acceptChallenge` | A request instructing the payment gateway to accept a previously challenged transaction. |
             *         | `denyChallenge` | A request instructing the payment gateway to deny a previously challenged transaction. |
             *         | `finalize` | A request instructing the payment gateway to finalize an asynchronous operation. |
             * @example capture
             * @enum {string}
             */
            operation: 'capture' | 'refund' | 'cancel' | 'acceptChallenge' | 'denyChallenge' | 'finalize';
            /**
             * @description Base currency for this order. This three-character currency code complies with ISO 4217.
             * @example EUR
             * @enum {string}
             */
            currency?: string;
            /**
             * @description Amount is required for partial maintenances. Do not specify amount for full captures or refunds.
             * @example 3.5
             */
            amount?: string;
            /**
             * @description Operation merchant ID. This value will be returned to merchant with the notifications related to this operation.
             * @example 204OJ23LKJ234
             */
            operation_id?: string;
            /**
             * @description Shopping cart details. **You must send only items that must be captured or refunded.**
             *
             *         Please refer to [HiPay Enterprise - Payment Gateway - Shopping cart managment](https://support.hipay.com/hc/fr/articles/115001660469-Payment-Gateway-Shopping-cart-management) technical documentation.
             */
            basket?: string;
            /**
             * @description Number of the subtransaction to be refunded.
             * @example 134470136955
             */
            sub_transaction_reference?: string;
            /**
             * @description To identify the origin of the transaction. Here are the authorized values for source property:
             *
             *         `AUTO`, `SAPI`, `CONS`, `PAGE`, `TPE`, `RTRY`, `MANU`, `PREF`, `REVI`, `CMS`, `SSDK`, `CSDK`
             * @example {"integration_version":"1.9.0","brand":"DEVPORTAL","source":"CSDK","brand_version":"12.2.0"}
             */
            source?: string;
        };
        /**
         * Operation
         * @description Operation model
         */
        Operation: {
            /**
             * @description The operation to perform on the transaction.
             * @example capture
             * @enum {string}
             */
            operation?: 'capture' | 'refund' | 'cancel' | 'acceptChallenge' | 'denyChallenge';
            /** @example 00001326589 */
            mid?: string;
            /** @example author */
            authorizationCode?: string;
            /** @example 800000968431 */
            transactionReference?: string;
            /** @example 118 */
            status?: string;
            /** @example Captured */
            message?: string;
            /** @example 2019-02-07T10:07:09+0000 */
            dateCreated?: string;
            /** @example 2019-02-07T10:07:09+0000 */
            dateUpdated?: string;
            /** @example 2019-02-07T10:07:09+0000 */
            dateAuthorized?: string;
            /** @example 125.85 */
            authorizedAmount?: string;
            /** @example 125.85 */
            capturedAmount?: string;
            /** @example 0.00 */
            refundedAmount?: string;
            /** @example 2 */
            decimals?: string;
            /** @example EUR */
            currency?: string;
        };
        /**
         * InputOrder
         * @description InputOrder model
         */
        InputOrder: {
            /**
             * @description The payment method used to proceed checkout. Depending on the payment product, parameters specific to the payment method are required. The list of payment products to display on the payment page.
             * @example visa
             * @enum {string}
             */
            payment_product:
                | 'visa'
                | 'mastercard'
                | 'maestro'
                | 'cb'
                | '3xcb'
                | '3xcb-no-fees'
                | '4xcb'
                | '4xcb-no-fees'
                | 'american-express'
                | 'bank-transfer'
                | 'bcmc'
                | 'bcmc-mobile'
                | 'cbc-online'
                | 'dexia-directnet'
                | 'giropay'
                | 'ideal'
                | 'ing-homepay'
                | 'kbc-online'
                | 'paypal'
                | 'paysafecard'
                | 'payulatam'
                | 'przelewy24'
                | 'qiwi-wallet'
                | 'sdd'
                | 'sisal'
                | 'sofort-uberweisung'
                | 'yandex'
                | 'aura'
                | 'boleto-bancario'
                | 'oxxo'
                | 'itau'
                | 'payshop'
                | 'dankort'
                | 'postepay'
                | 'ukash'
                | 'mercadopago'
                | 'webmoney-transfer'
                | 'diners'
                | 'jcb'
                | 'dcb-cz-tmobile'
                | 'dcb-cz-o2'
                | 'dcb-cz-vodafone'
                | 'dcb-at-tmobile'
                | 'dcb-at-a1'
                | 'dcb-at-orange'
                | 'dcb-at-drei'
                | 'dcb-be-mobistar'
                | 'dcb-it-mobilepay'
                | 'sct'
                | 'elo-card'
                | 'dcb-be-proximus'
                | 'postfinance-card'
                | 'postfinance-efinance'
                | 'carte-cadeau'
                | 'mybank'
                | 'safetypay'
                | 'skrill'
                | 'bnpp-4xcb'
                | 'bnpp-3xcb'
                | 'unionpay'
                | 'multi-payment'
                | 'discover'
                | 'sepa-refund-transfer'
                | 'banco-do-brasil'
                | 'bradesco'
                | 'carte-accord'
                | 'caixa'
                | 'edankort'
                | 'multibanco'
                | 'dcb-es-pagosmovistar'
                | 'cashu'
                | 'moneybookers'
                | 'afterpay'
                | 'cofinoga'
                | 'aurore'
                | '1eurocom'
                | 'hipercard'
                | 'santander-home-banking'
                | 'santander-cash'
                | 'banamex'
                | 'bbva-bancomer'
                | 'ecarte-bleue'
                | 'credit-long'
                | 'carte-titre-restaurant'
                | 'divido'
                | 'bacs'
                | 'tpe'
                | 'wechatpay'
                | 'sofort-lastschrift'
                | 'sepa-direct-debit'
                | 'cup'
                | 'bancontactqrcode';
            /**
             * @description **This parameter is specific to the PSD2.**
             *
             *     Browser Information
             */
            browser_info?: {
                /**
                 * @description Boolean that represents the ability of the cardholder browser to execute Java.
                 * @example true
                 */
                java_enabled?: boolean;
                /**
                 * @description Boolean that represents the ability of the cardholder browser to execute JavaScript.
                 * @example true
                 */
                javascript_enabled?: boolean;
                /**
                 * @description Customer’s IP address.
                 * @example 127.0.0.1
                 */
                ipaddr?: string;
                /**
                 * @description This element should contain the exact content of the HTTP Accept header as sent to the merchant from the customer’s browser.
                 * @example *\/*
                 */
                http_accept?: string;
                /**
                 * @description This element should contain the exact content of the HTTP User-Agent header as sent to the merchant from the customer’s browser.
                 * @example Mozilla/4.0
                 */
                http_user_agent?: string;
                /**
                 * @description Value representing the browser language as defined in IETF BCP47.
                 * @example fr-FR
                 */
                language: string;
                /**
                 * @description Value representing the bit depth of the colour palette for displaying images, in bits per pixel.
                 *
                 *     * `1` : 1 bit
                 *     * `4` : 4 bits
                 *     * `8` : 8 bits
                 *     * `15` : 15 bits
                 *     * `16` : 16 bits
                 *     * `24` : 24 bits
                 *     * `32` : 32 bits
                 *     * `48` : 48 bits
                 * @example 1
                 * @enum {integer}
                 */
                color_depth?: 1 | 4 | 8 | 15 | 16 | 24 | 32 | 48;
                /** @description Total height of the Cardholder’s screen in pixels. */
                screen_height?: number;
                /** @description Total width of the cardholder’s screen in pixels. */
                screen_width?: number;
                /**
                 * @description Time-zone offset in minutes between UTC and the Cardholder browser local time.
                 * @example -120
                 */
                timezone?: string;
                /**
                 * @description This element should contain the value of the ioBB hidden field.
                 * @example 042q0aAXOogFCkNMNf94lis1ztsdwpJAn3AFS6wesUIr2q
                 */
                device_fingerprint?: string;
            };
        } & WithRequired<components['schemas']['Common'], 'orderid' | 'description' | 'currency' | 'amount'> &
            WithRequired<components['schemas']['Order'], 'cardtoken'>;
        /**
         * Error
         * @description Error model
         */
        Error: {
            /** @description Code */
            code?: number;
            /** @description Message */
            message?: string;
            /** @description Description */
            description?: string;
        };
        /**
         * Transaction detail
         * @description Transaction detail
         */
        TransactionDetail: {
            transaction?: components['schemas']['Transaction'];
        };
        /**
         * Common
         * @description Common model
         */
        Common: {
            /**
             * @description Unique order ID.
             * @example ORDER_1537532589263
             */
            orderid?: string;
            /**
             * @description Transaction type:
             *          * `Sale` indicates that the transaction is automatically submitted for capture.
             *          * `Authorization` indicates that this transaction is sent for authorization only.
             * @example Authorization
             * @enum {string}
             */
            operation?: string;
            /**
             * @description Shopping cart details.
             *
             *         Please refer to [HiPay Enterprise - Payment Gateway - Shopping cart managment](https://support.hipay.com/hc/fr/articles/115001660469-Payment-Gateway-Shopping-cart-management) technical documentation.
             * @example [{"european_article_numbering":"4711892728946","product_reference":"NF-a1690","name":"My first product","type":"good","quantity":1,"unit_price":8.99,"discount":0,"tax_rate":"8.20","total_amount":8.99}]
             */
            basket?: string;
            /**
             * @description The order short description.
             * @example A super short description here...
             */
            description?: string;
            /**
             * @description Additional order description. You can show this description in HiPay payment page if desired.
             * @example A super long description here...
             */
            long_description?: string;
            /**
             * @description Base currency for this order. This three-character currency code complies with ISO 4217.
             * @example EUR
             * @enum {string}
             */
            currency?: string;
            /**
             * @description Total order amount, calculated as the sum of purchased items, plus shipping fees (if present), plus tax fees (if present).
             * @example 8.99
             */
            amount?: number;
            /**
             * @description The order shipping fee. It can be omitted if the shipping fee value is zero.
             * @example 1.3
             */
            shipping?: number;
            /**
             * @description The order tax fee. It can be omitted if the order tax value is zero.
             * @example 1.1
             */
            tax?: number;
            /**
             * @description The order tax rate.
             * @example 1
             */
            tax_rate?: number;
            /**
             * @description Merchant’s customer id. For fraud detection reasons.
             * @example 283749291
             */
            cid?: string;
            /**
             * @description The IP address of your customer making a purchase.
             * @example 127.0.0.1
             */
            ipaddr?: string;
            /**
             * @description The URL to return your customer to once the payment process is completed successfully.
             *
             *         For more information about the user redirection workflow, check the [HiPay Enterprise Overview](/getting-started/platform-hipay-enterprise/overview/#redirect-pages).
             * @example https://developer.hipay.com/simulator/success/
             */
            accept_url?: string;
            /**
             * @description The URL to return your customer to after the acquirer declines the payment.
             *
             *         For more information about the user redirection workflow, check the [HiPay Enterprise Overview](/getting-started/platform-hipay-enterprise/overview/#redirect-pages).
             * @example https://developer.hipay.com/simulator/decline/
             */
            decline_url?: string;
            /**
             * @description The URL to return your customer to when the payment request was submitted to the acquirer but response is not yet available.
             *
             *         For more information about the user redirection workflow, check the [HiPay Enterprise Overview](/getting-started/platform-hipay-enterprise/overview/#redirect-pages).
             * @example https://developer.hipay.com/simulator/pending/
             */
            pending_url?: string;
            /**
             * @description The URL to return your customer to after a system failure.
             *
             *         For more information about the user redirection workflow, check the [HiPay Enterprise Overview](/getting-started/platform-hipay-enterprise/overview/#redirect-pages).
             * @example https://developer.hipay.com/simulator/exception/
             */
            exception_url?: string;
            /**
             * @description The URL to return your customer to after a system failure.
             *
             *         For more information about the user redirection workflow, check the [HiPay Enterprise Overview](/getting-started/platform-hipay-enterprise/overview/#redirect-pages).
             * @example https://developer.hipay.com/simulator/cancel/
             */
            cancel_url?: string;
            /**
             * @description This field allows you to override the notification URL, available in the configuration in the HiPay back office, with the URL of your choice that will process the notification sent by the HiPay platform.
             * @example https://developer.hipay.com/simulator/notify/
             */
            notify_url?: string;
            /**
             * @description This element should contain the exact content of the HTTP Accept header as sent to the merchant from the customer’s browser.
             * @example *\/*
             */
            http_accept?: string;
            /**
             * @description This element should contain the exact content of the HTTP User-Agent header as sent to the merchant from the customer’s browser.
             * @example Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0)
             */
            http_user_agent?: string;
            /**
             * @description Locale code of your customer. This will be used to display payment page in correct language.
             * @example en_GB
             */
            language?: string;
            /**
             * @description Custom data. You can use these parameters to submit custom values you wish to show in HiPay back office transaction details, receive back in the API response messages, in the notifications or to activate specific FPS rules. Please note that cdata have been deprecated. If you are still using them, they can’t be combined with custom data. We thus recommend migrating to custom data as soon as possible.
             * @example {"internal_reference":"ORD_987465","customer_first_order":true,"other_sample_parameter":"Other sample value"}
             */
            custom_data?: string;
            /**
             * @deprecated
             * @description Custom data 1. Deprecated, please use *custom_data* parameter.
             */
            cdata1?: string;
            /**
             * @deprecated
             * @description Custom data 2. Deprecated, please use *custom_data* parameter.
             */
            cdata2?: string;
            /**
             * @deprecated
             * @description Custom data 3. Deprecated, please use *custom_data* parameter.
             */
            cdata3?: string;
            /**
             * @deprecated
             * @description Custom data 4. Deprecated, please use *custom_data* parameter.
             */
            cdata4?: string;
            /**
             * @deprecated
             * @description Custom data 5. Deprecated, please use *custom_data* parameter.
             */
            cdata5?: string;
            /**
             * @deprecated
             * @description Custom data 6. Deprecated, please use *custom_data* parameter.
             */
            cdata6?: string;
            /**
             * @deprecated
             * @description Custom data 7. Deprecated, please use *custom_data* parameter.
             */
            cdata7?: string;
            /**
             * @deprecated
             * @description Custom data 8. Deprecated, please use *custom_data* parameter.
             */
            cdata8?: string;
            /**
             * @deprecated
             * @description Custom data 9. Deprecated, please use *custom_data* parameter.
             */
            cdata9?: string;
            /**
             * @deprecated
             * @description Custom data 10. Deprecated, please use *custom_data* parameter.
             */
            cdata10?: string;
            /**
             * @description **This parameter is specific to SEPA Direct Debit as well as credit or debit card payment products.**
             *
             *         Electronic Commerce Indicator (ECI).
             *
             *         The ECI indicates the security level at which the payment information is processed between the cardholder and merchant.
             *
             *         ### Credit or debit card
             *
             *         If the payment product is a credit or debit card:
             *          * `1`: MO/TO (Mail Order/Telephone Order)
             *          * `2`: MO/TO – Recurring
             *          * `7`: E-commerce with SSL/TLS Encryption
             *          * `9`: Recurring E-commerce
             *          * `10`: TPE payment
             *
             *         A default ECI value can be set in the preferences page. An ECI value sent along in the transaction will overwrite the default ECI value.
             *
             *         ### SEPA Direct Debit
             *
             *         If the payment product is SEPA Direct Debit:
             *          * `7`: First transaction/one-shot transaction
             *          * `9`: Recurring transaction
             * @example 9
             * @enum {string}
             */
            eci?: string;
            /**
             * @description **This parameter is specific to SEPA Direct Debit as well as credit or debit card payment products.**
             *
             *         ### Credit or debit card
             *
             *         If the payment product is a credit or debit card, this parameter indicates if the 3-D Secure authentication should be performed for this transaction.
             *          * `0`: Bypass 3-D Secure authentication.
             *          * `1`: 3-D Secure authentication if available.
             *          * `2`: 3-D Secure authentication mandatory.
             *
             *         For more information about the 3-D Secure workflow, check the [HiPay Enterprise Overview](/getting-started/platform-hipay-enterprise/overview/#3-d-secure-integration).
             *
             *         ### SEPA Direct Debit
             *
             *         If the payment product is SEPA Direct Debit, this parameter indicates if the debit agreement (mandate) must be electronically signed or not.
             *          * `0`: Bypass electronic signature.
             *          * `1`: Ask for electronic signature.
             *
             *         For more information about the SEPA Direct Debit integration (including examples), check the [HiPay Enterprise Overview](/getting-started/platform-hipay-enterprise/overview/#sepa-direct-debit-sdd).
             * @example 0
             * @enum {string}
             */
            authentication_indicator?: string;
            /**
             * @description **This parameter is specific to provider COMPRAFACIL/SIBS.**
             *
             *         Validity period of the payment code in days.
             * @example 3
             */
            expiration_limit?: string;
            /**
             * @description **This parameter is specific to providers QIWIWALLET.**
             *
             *         Origin of payment.
             * @example web
             */
            payment_connectivity?: string;
            /**
             * @description **This parameter is specific to provider ONEY (Gift Card).**
             *          *
             *          * Gift Card number.
             * @example 6086300010000022383=35121011031363497
             */
            prepaid_card_number?: string;
            /**
             * @description **This parameter is specific to provider ONEY (Gift Card).**
             *          *
             *          * Gift Card CVC.
             * @example 123
             */
            prepaid_card_security_code?: string;
            /**
             * @description **This parameter is specific to providers PAGOSMOVISTAR and MOBILEPAY, only into the discover.**
             *
             *         Website identifier.
             * @example STWAK4897048
             */
            website_id?: string;
        };
        /**
         * Order
         * @description Order model
         */
        Order: {
            /**
             * @description The customer’s e-mail address.
             * @example john.doe@foobar99.com
             */
            email?: string;
            /**
             * @description **This parameter is specific to Astropay payment methods.**
             *
             *         Customer’s personal identification number.
             * @example AA 01 23 44 B
             */
            national_identification_number?: string;
            /**
             * @description The customer’s phone number.
             * @example 33012345678
             */
            phone?: string;
            /**
             * @description **This parameter is specific to the 3x and 4x Carte Bancaire payment products.**
             *
             *         The customer’s ship-to mobile phone number.
             * @example 33612345678
             */
            msisdn?: string;
            /**
             * @description Birth date of the customer (YYYYMMDD). For fraud detection reasons.
             * @example 19880612
             */
            birthdate?: string;
            /**
             * @description Gender of the customer:
             *          * `M`: male
             *          * `F`: female
             *          * `U`: unknown
             * @example U
             * @enum {string}
             */
            gender?: 'U' | 'F' | 'M';
            /**
             * @description The customer’s first name. This value will be use to pre-fill cardholder name on credit card payment form.
             * @example Cathy
             */
            firstname?: string;
            /**
             * @description The customer’s last name. This value will be use to pre-fill cardholder name on credit card payment form.
             * @example Doe
             */
            lastname?: string;
            /**
             * @description **This parameter is specific to provider PAYON.**
             *
             *         The customer’s card holder.
             * @example Cathy Doe
             */
            card_holder?: string;
            /**
             * @description Additional information about the customer (e.g., quality or function, company name, department, etc.).
             * @example Dr.
             */
            recipientinfo?: string;
            /**
             * @description House extension of the customer.
             * @example B
             */
            house_extension?: string;
            /**
             * @description House number of the customer.
             * @example 101
             */
            house_number?: string;
            /**
             * @description Street address of the customer.
             * @example 101 Rue de Rivoli
             */
            streetaddress?: string;
            /**
             * @description Additional address information of the customer (e.g., building, floor, flat, etc.).
             * @example Immeuble B
             */
            streetaddress2?: string;
            /**
             * @description The customer’s city.
             * @example Paris
             */
            city?: string;
            /** @description The USA state or the Canada state of the customer making the purchase. Send this information only if the address country of the customer is US (USA) or CA (Canada). */
            state?: string;
            /**
             * @description The zip or postal code of the customer.
             * @example 75001
             */
            zipcode?: string;
            /**
             * @description The zip or postal code of the customer.
             * @example FR
             */
            country?: string;
            /**
             * @description The first name of the order recipient.
             * @example Cathy
             */
            shipto_firstname?: string;
            /**
             * @description The last name of the order recipient.
             * @example Doe
             */
            shipto_lastname?: string;
            /**
             * @description Additional information about the order recipient (e.g., quality or function, company name, department, etc.).
             * @example Dr.
             */
            shipto_recipientinfo?: string;
            /**
             * @description House number of the recipient.
             * @example 101
             */
            shipto_house_number?: string;
            /**
             * @description Street address to which the order is to be shipped.
             * @example 101 Rue de Rivoli
             */
            shipto_streetaddress?: string;
            /**
             * @description The additional information about address to which the order is to be shipped (e.g., building, floor, flat, etc.).
             * @example Immeuble B
             */
            shipto_streetaddress2?: string;
            /**
             * @description The city to which the order is to be shipped.
             * @example Paris
             */
            shipto_city?: string;
            /** @description The USA state or Canada state to which the order is being shipped. Send this information only if the shipping country is US (USA) or CA (Canada). */
            shipto_state?: string;
            /**
             * @description The zip or postal code to which the order is being shipped.
             * @example 75001
             */
            shipto_zipcode?: string;
            /**
             * @description Country code to which the order is being shipped. This two-letter country code complies with ISO 3166-1 (alpha 2).
             * @example FR
             */
            shipto_country?: string;
            /**
             * @description This element should contain the value of the 'ioBB' hidden field.
             *
             *         For more information about the device fingerprint integration, check the [HiPay Enterprise Overview](/getting-started/platform-hipay-enterprise/overview/#device-fingerprint-integration).
             * @example 042q0aAXOogFCkNMNf94lis1ztsdwpJAn3AFS6wesUIr2q
             */
            device_fingerprint?: string;
            /**
             * @description To identify the origin of the transaction. Here are the authorized values for source property:
             *
             *         `AUTO`, `SAPI`, `CONS`, `PAGE`, `TPE`, `RTRY`, `MANU`, `PREF`, `REVI`, `CMS`, `SSDK`, `CSDK`
             * @example {"integration_version":"1.9.0","brand":"DEVPORTAL","source":"CSDK","brand_version":"12.2.0"}
             */
            source?: string;
            /**
             * @description **This parameter is specific to the iDEAL and the SEPA Direct Debit payment products.**
             *
             *         This is the Business Identifier Code (BIC) of the customer’s issuer bank.
             * @example BNPAFRPPXXX
             */
            issuer_bank_id?: string;
            /**
             * @description **This parameter is specific to the Qiwi Wallet payment product.**
             *
             *         The Qiwi user’s ID, whom the invoice is issued to. It is the user’s phone number, in international format.
             * @example 33670985712
             */
            qiwiuser?: string;
            /**
             * @description **This parameter is specific to the 3x and 4x Carte Bancaire payment products.**
             *
             *         Gender of the recipient:
             *          * `M`: male
             *          * `F`: female
             *          * `U`: unknown
             * @example U
             */
            shipto_gender?: string;
            /**
             * @description **This parameter is specific to the 3x and 4x Carte Bancaire payment products.**
             *
             *         The recipient’s ship-to phone number.
             * @example 33112345678
             */
            shipto_phone?: string;
            /**
             * @description **This parameter is specific to the 3x and 4x Carte Bancaire payment products.**
             *
             *         The recipient’s ship-to mobile phone number.
             * @example 3362345678
             */
            shipto_msisdn?: string;
            /**
             * @description **This parameter is specific to the 3x and 4x Carte Bancaire payment products.**
             *
             *         The order category code.
             *
             *         Please refer to the following list:
             *
             *         | Code | Description |
             *         | ---- | ----------- |
             *         | 5499 | Alimentation & gastronomie |
             *         | 5571 | Auto & moto |
             *         | 7929 | Culture & divertissements |
             *         | 5261 | Maison & jardin |
             *         | 5200 | Electroménager |
             *         | 7278 | Enchères et achats groupés |
             *         | 5193 | Fleurs & cadeaux |
             *         | 5734 | Informatique & logiciels |
             *         | 7298 | Santé & beauté |
             *         | 0 | Services aux particuliers |
             *         | 7361 | Services aux professionnels |
             *         | 5941 | Sport |
             *         | 5651 | Vêtements & accessoires |
             *         | 4722 | Voyage & tourisme |
             *         | 5946 | Hifi, photo & vidéos |
             *         | 4812 | Téléphonie & communication |
             * @example 5941
             * @enum {integer}
             */
            order_category_code?:
                | '5499'
                | '5571'
                | '7929'
                | '5261'
                | '5200'
                | '7278'
                | '5193'
                | '5734'
                | '7298'
                | '0'
                | '7361'
                | '5941'
                | '5651'
                | '4722'
                | '5946'
                | '4812';
            /**
             * @description **This parameter is specific to the 3x and 4x Carte Bancaire payment products.**
             *
             *         Estimated delivery date. Format is YYYY-MM-DD.
             * @example 2022-12-20
             */
            delivery_date?: string;
            /**
             * @description **This parameter is specific to the 3x and 4x Carte Bancaire payment products.**`
             *
             *         The delivery method.
             * @example CARRIER
             * @enum {string}
             */
            delivery_method?: 'EXPRESS24H' | 'EXPRESS48H' | 'STORE' | 'STORE24H' | 'CARRIER' | 'CARRIER24H' | 'RELAYPOINT' | 'RELAYPOINT24H';
            /**
             * @description **This parameter is specific to the 3x and 4x Carte Bancaire payment products.**
             *
             *         Carrier description.
             * @example La Poste, 27 Rue des Francs Bourgeois
             */
            carrier_description?: string;
            /**
             * @description **This parameter indicates if the payement should be a recurring payment (MO/TO - Recurring, Recurring E-commerce, Recurring SEPA DIRECT DEBIT transaction)**
             *
             *         Indicates if the debit agreement will be created for a single-use or a multi-use.
             *
             *         Possible values:
             *          * `0`: Generate a single-use agreement id.
             *          * `1`: Initiate a recurring payment use case
             * @example 0
             * @enum {string}
             */
            recurring_payment?: string;
            /**
             * @description Unique identifier for the debit agreement
             * @example 33452
             */
            debit_agreement_id?: number;
            /**
             * @description **This parameter indicates if the payment should be a one click payment.**`
             *
             *          * `1`: Initiate a one-click payment use case
             * @example 0
             * @enum {boolean}
             */
            one_click?: boolean;
            /**
             * @description **This parameter is specific to the SEPA Direct Debit payment product.**
             *
             *         International Bank Account Number (IBAN).
             * @example FR1420041010050500013M02606
             */
            iban?: string;
            /**
             * @description **This parameter is specific to the SEPA Direct Debit payment product.**
             *
             *         Issuer Bank Name.
             * @example BNP
             */
            bank_name?: string;
            /**
             * @description Sales channel :
             *          * `0`: Default.
             *          * `1`: Ecommerce API.
             *          * `2`: Hosted Payment Page.
             *          * `3`: POS.
             * @example
             * @enum {string}
             */
            sales_channel?: '0' | '1' | '2' | '3';
            /**
             * @description Billing descriptor for machine learning.
             * @example Dell Inspiron 15 3583 (i3583-3112BLK-PFR)
             */
            soft_descriptor?: string;
            /**
             * @description **This parameter is specific to credit or debit card payment products.**
             *
             *         This is the token obtained from the HiPay Enterprise Secure Vault API when tokenizing a credit or debit card. To generate a token, please refer to the [HiPay Enterprise Tokenization API documentation](/doc-api/enterprise/token/#/tokenization/createToken).
             * @example db0eef6bfd4cd30ae4e30dc46b89d375b977656d04249741d8b60f533ffa0020
             */
            cardtoken?: string;
            /**
             * @description The request ID linked to the token.
             * @example 7879454
             */
            request_id?: number;
            /**
             * @description **This parameter is specific to the PSD2.**
             *
             *         Merchant’s statement about the transaction he wants to proceed.
             */
            merchant_risk_statement?: {
                /**
                 * @description Email address to which the goods needs to be sent to.
                 * @example jane.doe@test.com
                 */
                email_delivery_address?: string;
                /**
                 * @description Indicates when the goods are willing to be received by the customer.
                 *          * `1` : ELECTRONIC DELIVERY
                 *          * `2` : SAME DAY SHIPPING
                 *          * `3` : OVERNIGHT SHIPPING
                 *          * `4` : TWO DAY OR MORE SHIPPING
                 * @example 1
                 * @enum {integer}
                 */
                delivery_time_frame?: 1 | 2 | 3 | 4;
                /**
                 * @description Availabilty of the goods.
                 *          * `1` : MERCHANDISE AVAILABLE
                 *          * `2` : FUTURE AVAILABILITY
                 * @example 1
                 * @enum {integer}
                 */
                purchase_indicator?: 1 | 2;
                /**
                 * @description For a pre-ordered purchase, the expected date that the merchandise will be available.
                 * @example 20190925
                 */
                pre_order_date?: number;
                /**
                 * @description Unicity of the order for the customer.
                 *          * `1` : FIRST TIME ORDERED
                 *          * `2` : REORDERED
                 * @example 1
                 * @enum {integer}
                 */
                reorder_indicator?: 1 | 2;
                /**
                 * @description Address to whom the goods are to be sent.
                 *          * `1` : SHIP TO CARDHOLDER'S BILLING ADDRESS
                 *          * `2` : SHIP TO ANOTHER VERIFIED ADDRESS ON FILE WITH MERCHANT
                 *          * `3` : SHIP TO ADDRESS THAT IS DIFFERENT THAN THE CARDHOLDER'S BILLING ADDRESS
                 *          * `4` : SHIP TO STORE / PICK UP AT LOCAL STORE
                 *          * `5` : DIGITAL GOODS
                 *          * `6` : TRAVEL AND EVENT TICKETS, NOT SHIPPED
                 *          * `7` : OTHER (Gaming, digital services not shipped, emedia subscriptions)
                 * @example 1
                 * @enum {integer}
                 */
                shipping_indicator?: 1 | 2 | 3 | 4 | 5 | 6 | 7;
                /** @description Information on order making throught a gift card. */
                gift_card?: {
                    /**
                     * @description Amount of the gift card.
                     * @example 15
                     */
                    amount?: number;
                    /**
                     * @description Total count of individual gift cards purchased.
                     * @example 0
                     */
                    count?: number;
                    /**
                     * @description Currency of the gift card.
                     * @example EUR
                     */
                    currency?: string;
                };
            };
            /**
             * @description **This parameter is specific to the PSD2.**
             *
             *         Information about the customer’s account on the merchant’s website.
             */
            account_info?: {
                /** @description Customer’s account information */
                customer?: {
                    /**
                     * @description Account's type of seniority, based on when the customer created their account on the merchant's website.
                     *          * `1` : Guest
                     *          * `2` : Created during this transaction
                     *          * `3` : Less than 30 days
                     *          * `4` : 30 - 60 days
                     *          * `5` : More than 60 days
                     * @example 1
                     * @enum {integer}
                     */
                    account_possession?: 1 | 2 | 3 | 4 | 5;
                    /**
                     * @description Customer’s last change on his account. (YYYYMMDD)
                     * @example 20180507
                     */
                    account_change?: number;
                    /**
                     * @description Date when the customer created his account on the merchant’s website. (YYYYMMDD)
                     * @example 20180507
                     */
                    opening_account_date?: number;
                    /**
                     * @description Date when the customer made a password change on his account. (YYYYMMDD)
                     * @example 20180507
                     */
                    password_change?: number;
                };
                /** @description Customer’s purchase information */
                purchase?: {
                    /**
                     * @description Number of purchases with the customer’s account during the last six months.
                     * @example 2
                     */
                    count?: number;
                    /**
                     * @description Number of attempts to add a card into the customer’s account in the last 24 hours.
                     * @example 0
                     */
                    card_stored_24h?: number;
                    /**
                     * @description Number of transactions (successful and abandoned) for this customer’s account across all payment accounts in the previous 24 hours.
                     * @example 0
                     */
                    payment_attempts_24h?: number;
                    /**
                     * @description Number of transactions (successful and abandoned) for this customer’s account across all payment accounts in the previous year.
                     * @example 0
                     */
                    payment_attempts_1y?: number;
                };
                /** @description Customer’s payment information */
                payment?: {
                    /**
                     * @description Date that the payment account was enrolled in the cardholder’s account with the 3DS Requestor.(YYYYMMDD)
                     * @example 20180507
                     */
                    enrollment_date?: number;
                };
                /** @description Customer’s shipping information */
                shipping?: {
                    /**
                     * @description Date when the shipping address used for this transaction was first used. (YYYYMMDD)
                     * @example 2
                     */
                    shipping_used_date?: number;
                    /**
                     * @description Indicates when the shipping address used for this transaction was first used with the merchant.
                     *          * `1` : THIS TRANSACTION
                     *          * `2` : LESS THAN 30 DAYS
                     *          * `3` : 30-60 DAYS
                     *          * `4` : MORE THAN 60 DAYS
                     * @example 1
                     * @enum {integer}
                     */
                    address_usage_duration?: 1 | 2 | 3 | 4;
                    /**
                     * @description Indicates if the Cardholder Name on the account is identical to the shipping Name used for this transaction.
                     *          * `1` : Account Name Identical to Shipping Name
                     *          * `2` : Account Name different than shipping Name
                     * @example 1
                     * @enum {integer}
                     */
                    name_indicator?: 1 | 2;
                    /**
                     * @description Indicates whether the merchant has experienced suspicious activity (including previous fraud) on the cardholder account.
                     *          * `1` : No suspicious activity has been observed
                     *          * `2` : Suspicious activity has been observed
                     * @example 1
                     * @enum {integer}
                     */
                    suspicious_activity?: 1 | 2;
                };
            };
            /**
             * @description **This parameter is specific to the PSD2.**
             *
             *         Channel through which the transaction is being processed. By default this value is set to 2.
             *          * `1` : App-based (APP)
             *          * `2` : Browser (BRW)
             *          * `3` : 3DS Requestor Initiated (3RI)
             * @example 1
             * @enum {integer}
             */
            device_channel?: 1 | 2 | 3;
            /**
             * @description **This parameter is specific to the PSD2.**
             *
             *         Information on recurring transaction
             */
            recurring_info?: {
                /**
                 * @description Date after which no further authorisations shall be performed. (YYYYMMDD)
                 * @example 20180507
                 */
                expiration_date: number;
                /**
                 * @description Indicates the minimum number of days between authorisations.
                 * @example 31
                 */
                frequency: number;
            };
        };
        /**
         * Order Response
         * @description Order Response model
         */
        OrderResponse: {
            /** @example 1549547828947 */
            id?: string;
            /** @example 2019-02-07T13:57:08+0000 */
            dateCreated?: string;
            /** @example 0 */
            attempts?: string;
            /** @example 125.75 */
            amount?: string;
            /** @example 0 */
            shipping?: string;
            /** @example 1.10 */
            tax?: string;
            /** @example 2 */
            decimals?: string;
            /** @example EUR */
            currency?: string;
            /** @example 283749291 */
            customerId?: string;
            /** @example en_GB */
            language?: string;
            /** @example john.doe@foobar99.com */
            email?: string;
            /** @example 125.75 */
            amount_to_capture?: string;
            /**
             * @description To indicate the preference for a frictionless flow during the authentication request, the merchant may send the sca_preference parameter.
             *         Depending on the merchant's assessment of the risk of fraud, specific values may be sent.
             *         This parameter can only be used by merchants who have a fraud risk assessment mechanism of their own and who have subscribed to the SCA Preference merchant option.
             *         Please contact your account manager to request it.
             *
             *         `1` : No Preference.
             *         If you are not sure about the transaction's risk of fraud, use this value. Using this value for all your transactions may result in a high strong customer authentication rate.
             *         `2` : No Challenge
             *         If you think this transaction is safe. This will tell the acquirer a frictionless flow is preferred.
             *         `3` : Challenge Requested
             *         If you think this transaction may be at risk, use this value. This will tell the acquirer that a strong customer authentication may be required, depending on the PSD2 specific information you sent along with the transaction.
             * @example 1
             * @enum {integer}
             */
            sca_preference?: 1 | 2 | 3;
        };
        /**
         * Debit Agreement
         * @description Debit Agreement model
         */
        debitAgreement: {
            id?: string;
            status?: string;
        };
        /**
         * Payment
         * @description Payment model
         */
        paymentMethod: {
            token?: string;
            brand?: string;
            pan?: string;
            /** @example 03 */
            cardExpiryMonth?: string;
            /** @example 2020 */
            cardExpiryYear?: string;
            /**
             * @description Name of the financial institution that
             *     issued the payment method.
             */
            issuer?: string;
            /**
             * @description The country code where payment method was issued.
             * @example US
             */
            country?: string;
            /** @example JOHN DOE */
            cardHolder?: string;
        };
        /**
         * Transaction
         * @description Transaction model
         */
        Transaction: {
            order?: components['schemas']['OrderResponse'];
            /** @example author */
            authorizationCode?: string;
            /** @example 2019-02-07T10:07:09+0000 */
            dateCreated?: string;
            /** @example 2019-02-07T10:07:09+0000 */
            dateAuthorized?: string;
            /** @example 125.85 */
            authorizedAmount?: string;
            /** @example 2 */
            decimals?: string;
            /** @example EUR */
            currency?: string;
            /** @example 0.0.0.0 */
            ipAddress?: string;
            /** @example 0.0.0.0 */
            ipCountry?: string;
            avsResult?: string;
            cvcResult?: string;
            threeDSecure?: components['schemas']['ThreeDSecure'];
            /**
             * @description Unique Transaction Identifier.
             * @example 800000790677
             */
            transactionReference?: string;
            /**
             * @description Attempt identifier.
             * @example 1
             */
            attemptId?: number;
            /**
             * @description Date of last status change.
             *
             *     This date must comply with ISO 8601.
             */
            dateUpdated?: string;
            /**
             * @description Transaction state.
             * @example completed
             */
            state?: string;
            /**
             * @description Merchant id (MID).
             *
             *     Unique identifier assigned to the merchant.
             */
            mid?: number;
            /**
             * @description Captured amount.
             * @example 125.75
             */
            capturedAmount?: string;
            /**
             * @description Refunded amount.
             * @example 00.00
             */
            refundedAmount?: string;
            /** @description Total credited. */
            creditedAmount?: string;
            /**
             * @description Chargebacked amount.
             * @example 125.75
             */
            chargebackedAmount?: string;
            /**
             * @description The payment product used for processing current transaction.
             * @example visa
             */
            paymentProduct?: string;
            /** @description The payment method used for processing current transaction. */
            paymentMethod?: components['schemas']['paymentMethod'];
            /**
             * @description Transaction status.
             * @example 116
             */
            status?: number;
            /** @description The numeric value of the error. */
            reason?: components['schemas']['reason'];
            /** @description URL of the page on which to redirect the customer. */
            forwardUrl?: string;
            deviceId?: string;
            /** @description Fraud screening result. */
            fraudScreening?: components['schemas']['fraud'];
            /**
             * @description Electronic Commerce Indicator (ECI).
             *
             *     The Electronic Commerce Indicator (ECI) is used by acquirers/issuers
             *     to determine the type of transaction being processed. The ECI value
             *     should represent the source of the transaction request. That is, the
             *     environment that the cardholder used to provide the payment card details
             *     to the merchant. It is important that merchants set the correct ECI
             *     value during transaction processing to ensure that appropriate merchant
             *     service rates are received.
             * @example 7
             */
            eci?: number;
            debitAgreement?: components['schemas']['debitAgreement'];
            message?: string;
        };
        /**
         * ThreeDSecure
         * @description ThreeDSecure model
         */
        ThreeDSecure: {
            /** @example 6 */
            eci?: string;
            /** @example N */
            enrollmentStatus?: string;
            /** @example Cardholder Not Enrolled */
            enrollmentMessage?: string;
            /** @example  */
            authenticationStatus?: string;
            /** @example  */
            authenticationMessage?: string;
            /** @example  */
            authenticationToken?: string;
            /** @example  */
            xid?: string;
        };
        /**
         * Reason
         * @description Reason model
         */
        reason: {
            code?: string;
            message?: string;
        };
        /**
         * Fraud screening
         * @description Fraud screening model
         */
        fraud: {
            /** @example 0 */
            scoring?: string;
            /** @example ACCEPTED */
            result?: string;
            /** @example  */
            review?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    performMaintenanceOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The unique identifier of the transaction.
                 * @example 800000420435
                 */
                transaction_reference: string;
            };
            cookie?: never;
        };
        /** @description Maintenance information */
        requestBody: {
            content: {
                'multipart/form-data': components['schemas']['Maintenance'];
            };
        };
        responses: {
            /** @description The maintenance operation was executed successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Operation'];
                };
            };
            /** @description The request was rejected due to a validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Error'];
                };
            };
            /** @description An authentication error occurred/invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Error'];
                };
            };
            /** @description Access to this resource is fordidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Error'];
                };
            };
            /** @description Transaction was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Error'];
                };
            };
        };
    };
    requestNewOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Order information */
        requestBody: {
            content: {
                'multipart/form-data': components['schemas']['InputOrder'];
            };
        };
        responses: {
            /** @description Order successfully created and transaction executed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Transaction'];
                };
            };
            /** @description The request was rejected due to a validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Error'];
                };
            };
            /** @description An authentication error occurred/invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Error'];
                };
            };
            /** @description Access to this resource is fordidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Error'];
                };
            };
        };
    };
    getTransactionByReference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The unique identifier of the transaction.
                 * @example 800000420435
                 */
                transaction_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['TransactionDetail'];
                };
            };
            /** @description The request was rejected due to a validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Error'];
                };
            };
            /** @description An authentication error occurred/invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Error'];
                };
            };
            /** @description Access to this resource is fordidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Error'];
                };
            };
        };
    };
    getTransactionsByReference: {
        parameters: {
            query: {
                /**
                 * @description Merchant unique order id. Return all the transactions related to an order id.
                 * @example ORDER_1487239265080
                 */
                orderid: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transactions retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['TransactionDetail'];
                };
            };
            /** @description The request was rejected due to a validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Error'];
                };
            };
            /** @description An authentication error occurred/invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Error'];
                };
            };
            /** @description Access to this resource is fordidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Error'];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
